INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'1.01', N'Uống', 1)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'1.02', N'Ngậm', 2)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'1.03', N'Nhai', 3)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'1.04', N'Đặt dưới lưỡi', 4)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'1.05', N'Ngậm dưới lưỡi', 5)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.01', N'Tiêm bắp', 6)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.02', N'Tiêm dưới da', 7)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.03', N'Tiêm trong da', 8)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.04', N'Tiêm tĩnh mạch', 9)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.05', N'Tiêm truyền tĩnh mạch', 10)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.06', N'Tiêm vào ổ khớp', 11)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.07', N'Tiêm nội nhãn cầu', 12)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.08', N'Tiêm trong dịch kính của mắt', 13)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.09', N'Tiêm vào các khoang của cơ thể', 14)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.10', N'Tiêm', 15)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.11', N'Tiêm động mạch khối u', 16)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.12', N'Tiêm vào khoang tự nhiên', 17)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.13', N'Tiêm vào khối u', 18)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.14', N'Truyền tĩnh mạch', 19)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'2.15', N'Tiêm truyền', 20)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'3.01', N'Bôi', 21)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'3.02', N'Xoa ngoài', 22)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'3.03', N'Dán trên da', 23)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'3.04', N'Xịt ngoài da', 24)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'3.05', N'Dùng ngoài', 25)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'4.01', N'Đặt âm đạo', 26)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'4.02', N'Đặt hậu môn', 27)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'4.03', N'Thụt hậu môn - trực tràng', 28)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'4.04', N'Đặt', 29)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'4.05', N'Đặt tử cung', 30)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'4.06', N'Thụt', 31)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.01', N'Phun mù', 32)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.02', N'Dạng hít', 33)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.03', N'Bột hít', 34)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.04', N'Xịt', 35)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.05', N'Khí dung', 36)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.06', N'Đường hô hấp', 37)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.07', N'Xịt mũi', 38)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.08', N'Xịt họng', 39)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.09', N'Thuốc mũi', 40)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'5.10', N'Nhỏ mũi', 41)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'6.01', N'Nhỏ mắt', 42)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'6.02', N'Tra mắt', 43)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'6.03', N'Thuốc mắt', 44)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'6.04', N'Nhỏ tai', 45)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.01', N'Áp ngoài da', 46)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.02', N'Áp sát khối u', 47)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.03', N'Bình khí lỏng hoặc nén', 48)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.04', N'Bình khí nén', 49)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.05', N'Bôi trực tràng', 50)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.06', N'Đánh tưa lưỡi', 51)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.07', N'Cấy vào khối u', 52)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.08', N'Chiếu ngoài', 53)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.09', N'Dung dịch', 54)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.10', N'Dung dịch rửa', 55)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.11', N'Dung dịch thẩm phân', 56)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.12', N'Phun', 57)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.13', N'Túi', 58)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.14', N'Hỗn dịch', 59)
INSERT [Usage_BHYT] ([UsageCode], [UsageName], [STT]) VALUES (N'9.15', N'Bột đông khô để pha hỗn dịch', 60)